# site settings
title: Acción Climática
email: fperry@ciudadaniai.org
description: 'Monitoreo sobre la inclusión de los derechos de la niñez en la nueva constitución'
baseurl: '//accionporelclima.cl/' # the subpath of your site, e.g. /blog/
url: 'https://accionporelclima.cl' # the base hostname & protocol for your site
# analytics: 'G-ES8KVYN4W6' # google analytics tracking code
launched: true
# build settings
markdown: kramdown
# notas y cosas finales
final_mark: 5.8
final_percentage: 75
