# site settings
title: Acci칩n Clim치tica
email: fperry@ciudadaniai.org
description: 'Acci칩n Clim치tica - Del Dicho al Hecho - Chile'
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://accionclimaticachile.cl' # the base hostname & protocol for your site
# analytics: 'G-ES8KVYN4W6' # google analytics tracking code
launched: true
# build settings
markdown: kramdown
# notas y cosas finales
final_mark: 5.9
final_percentage: 75