# site settings
title: Vigilantes
email: prensa@ciudadanointeligente.org
description: 'Vigilantes.'
baseurl: '//ciudadanointeligente.org/vigilantes/' # the subpath of your site, e.g. /blog/
url: 'https://ciudadanointeligente.org/vigilantes' # the base hostname & protocol for your site
analytics: 'UA-41822715-9' # google analytics tracking code
twitter_username: ciudadanoi
launched: true
# build settings
markdown: kramdown
# notas y cosas finales
final_mark: 4.5
final_percentage: 50
