# site settings
title: Ni침ez Constituye
email: observatorio@paralaconfianza.com
description: 'Monitoreo sobre la inclusi칩n de los derechos de la ni침ez en la nueva constituci칩n'
baseurl: '//ninezconstituye.cl/' # the subpath of your site, e.g. /blog/
url: 'https://ninezconstituye.cl' # the base hostname & protocol for your site
# analytics: 'G-ES8KVYN4W6' # google analytics tracking code
launched: true
# build settings
markdown: kramdown
# notas y cosas finales
final_mark: 5.8
final_percentage: 71
